config/routes.rb
Rails.application.routes.draw do

  get "sales/new"

  root "welcome#index"
  resources :foods do
    resources :comments
  end
  
  resources :categories
  resources :cart_items
  resources :carts
  resources :administrator
  resources :about
  resources :sales
  resources :users do
    resources :orders
  end

  get "display/:option" => "sales#display", as: "display"
  get "login" => "sessions#new"
  get "/payment/processed" => "checkout#create", as: :get_payment_completed
  get "admin" => "administrator#show", as: :dashboard
  get "admin/foods" => "administrator#food_index", as: :admin_foods
  get "admin/orders" => "administrator#order_index", as: :admin_orders
  get "admin/users" => "administrator#user_index", as: :admin_users
  get "admin/sales" => "administrator#sale_index", as: :admin_sales
  get "admin/categories" => "administrator#category_index",
      as: :admin_categories
  post "login" => "sessions#create"
  post "checkout" => "checkout#show", as: :checkout
  post "carts/checkout" => "carts#checkout", as: :cart_checkout
  post "payment" => "checkout#create", as: :payment
  post "/foods/:food_id/comments(.:format)" => "comments#create",
       as: :create_food_comment
  post "/payment/processed" => "checkout#create", as: :payment_completed
  patch "order_status" => "administrator#update", as: :order_status
  patch "/foods/:food_id/edit_status" => "foods#edit_status", as: :edit_status
  delete "logout" => "sessions#destroy"
  delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete

end

app/models/cart.rb
class Cart
	attr_reader :cart_data

	def initialize(cart_data)
    @cart_data = cart_data || {}
	end

	def increment(item_id)
	  @cart_data[item_id] ||= 0
	  increment_cart_item_by_one(item_id)
	end

	def destroy
	  @cart_data = nil
	end

	def delete
		@cart_data[item_id] = 0
	end

	private

	def increment_cart_item_by_one(item_id)
	  @cart_data[item_id] += 1
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart_items = session[:cart]
    @ordered_foods = {}
    @total = 0
    @pickup_time = 0
    @cart_items.each do |food_id, qty, prep_time|
      food = Food.find_by_id(food_id)
      prep_time = line_prep_total(qty, food.prep_time).to_i 
      @ordered_foods[food_id] = { food: food, qty: qty, prep_time: prep_time }
      check_food_status(food, qty, food_id, prep_time)
      @pickup_time += prep_time
      @total_pickup_time = add_extra_time(@pickup_time)
    end unless session[:cart].nil?
    @current_order.ordered_items = @ordered_foods
    session[:order]["details"]["pickup_time"] = @total_pickup_time
    session[:order]["items"] = @ordered_foods
  end

  def destroy
    food_id = params[:id]
    @cart.cart_data.delete(food_id)
    redirect_to carts_path
  end

  def check_food_status(food, qty, food_id, prep_time)
    unless food.status == "available"
      @ordered_foods.delete(food_id)
    else
      price =  food.sales[:status] ? food.sales[:price] : food.price
      @total += (price * qty)
    end
  end

private

  def line_prep_total(qty, prep_time) 
    added_time = ((qty/7) * 10) + prep_time
  end

  def add_extra_time(pick_up_time)
    unless Order.first.nil?
      if (Order.first.Status != "Delivered")
        pick_up_time + 4
      else 
        pick_up_time
      end
    else
    pick_up_time
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

<div class="full-height scroll-bar">
  <div class="pad-bottom">
  <% if @ordered_foods.length == 0 %>
      <p>Your cart is empty</p>
  <% else %>
  <table class="hoverable">
    <thead>
      <tr style="background-color:#BCAAA4;">
        <th data-field="id">S/N</th>
        <th data-field="name">Name</th>
        <th data-field="description">Description</th>
        <th data-field="quantity">Quantity</th>
        <th data-field="quantity">Delivery Time</th>
        <th data-field="price">Price</th>
        <th data-field="line total">Line Total</th>
      </tr>
    </thead>
    <tbody>

    <% @ordered_foods.each do |index, details| %>
      <% food_id = details[:food][:id] %>
        <tr>
          <td><%= index %></td>
          <td id="food_name_<%= food_id %>"><%= details[:food]['name'] %></td>
          <td id="food_desc_<%= food_id %>"><%= details[:food]['description'] %></td>
          <td id="food_qty_<%= food_id %>"><%=form_for 'quantity', :url => {:controller => 'cart_items', :action => 'update', food_id: details[:food][:id], id: index }, method: :patch  do |f| %>
            <%= f.number_field details[:qty], :min => 1, :value => details[:qty], :class => "qty qty-editable-width", "data-message" => food_id %>
            <% end %>
          </td>
          <td class="food-prep" class="food_prep_<%= food_id %>" id="food_prep_<%= food_id %>" data-message="<%= details[:food]['prep_time'] %>"><%= details[:prep_time] %> mins </td>
          <% if details[:food]['sales'][:status] %>
            <td id="food_unit_price_<%= food_id %>"><%= details[:food]['sales'][:price] %></td>
            <td>N<span class="line-total" id="food_sub_total_<%= details[:food][:id] %>" data-message="<%= details[:food]['sales'][:price] %>" ><%= details[:food]['sales'][:price].to_i * details[:qty].to_i %></span></td>
          <% else %>
            <td id="food_unit_price_<%= food_id %>"><%= details[:food]['price'] %></td>
          <td>N<span class="line-total" id="food_sub_total_<%= details[:food][:id] %>" data-message="<%= details[:food]['price'] %>" ><%= details[:food]['price'].to_i * details[:qty].to_i %></span></td>
          <% end %>
          <td>
            <%= button_to cart_item_delete_path(details[:food][:id]), :class => "clear-button", method: :delete  do %>
              <i class="material-icons">clear</i>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
      <tfoot>
        <tr style="border-top:2px solid #3e2511">
          <td></td>
          <td></td>
          <td id="prep_total">Your food will be ready in <%= time_ago_in_words(@total_pickup_time.minutes.from_now)%> MAX</td>
          <td></td>
          <td></td>
          <td>Subtotal</td>
          <td id="total">N<%= @total%></td>
        </tr>
      </tfoot>
    </table>
    <%= button_to 'Checkout', checkout_path, :class => "btn" %>
    <% end %>
  </div>
</div>